from ortools.linear_solver.python import model_builder


# Create a ModelBuilder object
model = model_builder.ModelBuilder()



#model.import_from_mps_file(mps_path)
model.import_from_mps_string('''
* Generated by MPModelProtoExporter
*   Name             : 
*   Format           : Free
*   Constraints      : 212
*   Variables        : 311
*     Binary         : 0
*     Integer        : 0
*     Continuous     : 311
NAME          
ROWS
 N  COST
 E  C000
 E  C001
 E  C002
 E  C003
 E  C004
 E  C005
 E  C006
 E  C007
 E  C008
 E  C009
 E  C010
 E  C011
 E  C012
 E  C013
 E  C014
 E  C015
 E  C016
 E  C017
 E  C018
 E  C019
 E  C020
 E  C021
 E  C022
 E  C023
 E  C024
 E  C025
 E  C026
 E  C027
 E  C028
 E  C029
 E  C030
 E  C031
 E  C032
 E  C033
 E  C034
 E  C035
 G  C036
 N  C037
 N  C038
 N  C039
 N  C040
 N  C041
 N  C042
 N  C043
 N  C044
 N  C045
 N  C046
 N  C047
 N  C048
 N  C049
 N  C050
 N  C051
 N  C052
 N  C053
 N  C054
 N  C055
 N  C056
 N  C057
 N  C058
 N  C059
 N  C060
 N  C061
 N  C062
 N  C063
 N  C064
 N  C065
 N  C066
 N  C067
 N  C068
 N  C069
 N  C070
 N  C071
 N  C072
 N  C073
 N  C074
 N  C075
 N  C076
 N  C077
 N  C078
 N  C079
 N  C080
 N  C081
 N  C082
 N  C083
 N  C084
 N  C085
 N  C086
 N  C087
 N  C088
 N  C089
 N  C090
 N  C091
 N  C092
 N  C093
 N  C094
 N  C095
 N  C096
 N  C097
 N  C098
 N  C099
 N  C100
 N  C101
 N  C102
 N  C103
 N  C104
 N  C105
 N  C106
 N  C107
 N  C108
 N  C109
 N  C110
 N  C111
 N  C112
 N  C113
 N  C114
 N  C115
 N  C116
 N  C117
 N  C118
 N  C119
 N  C120
 N  C121
 N  C122
 N  C123
 N  C124
 N  C125
 N  C126
 N  C127
 N  C128
 N  C129
 N  C130
 N  C131
 N  C132
 N  C133
 N  C134
 N  C135
 N  C136
 N  C137
 N  C138
 N  C139
 N  C140
 N  C141
 N  C142
 N  C143
 N  C144
 N  C145
 N  C146
 N  C147
 N  C148
 N  C149
 N  C150
 N  C151
 N  C152
 N  C153
 N  C154
 N  C155
 N  C156
 N  C157
 N  C158
 N  C159
 N  C160
 N  C161
 N  C162
 N  C163
 N  C164
 N  C165
 N  C166
 N  C167
 N  C168
 N  C169
 N  C170
 N  C171
 N  C172
 N  C173
 N  C174
 N  C175
 N  C176
 N  C177
 N  C178
 N  C179
 N  C180
 N  C181
 N  C182
 N  C183
 N  C184
 N  C185
 N  C186
 N  C187
 N  C188
 N  C189
 N  C190
 N  C191
 N  C192
 N  C193
 N  C194
 N  C195
 N  C196
 N  C197
 N  C198
 N  C199
 N  C200
 N  C201
 N  C202
 N  C203
 N  C204
 N  C205
 N  C206
 N  C207
 N  C208
 N  C209
 N  C210
 N  C211
COLUMNS
    V000    COST              1  C000              1
    V001    COST              1  C001              1
    V002    COST              1  C002              1
    V003    COST              1  C003              1
    V004    COST              1  C004              1
    V005    COST              1  C005              1
    V006    COST              1  C006              1
    V007    COST              1  C007              1
    V008    COST              1  C008              1
    V009    COST              1  C009              1
    V010    COST              1  C010              1
    V011    COST              1  C011              1
    V012    COST              1  C012              1
    V013    COST              1  C013              1
    V014    COST              1  C014              1
    V015    COST              1  C015              1
    V016    COST              1  C016              1
    V017    COST              1  C017              1
    V018    COST              1  C018              1
    V019    COST              1  C018             -1
    V019    C036              1
    V020    COST              1  C019              1
    V021    COST              1  C020              1
    V022    COST              1  C021              1
    V023    COST              1  C022              1
    V024    COST              1  C023              1
    V025    COST              1  C024              1
    V026    COST              1  C025              1
    V027    COST              1  C026              1
    V028    COST              1  C027              1
    V029    COST              1  C028              1
    V030    COST              1  C028             -1
    V030    C036              1
    V031    COST              1  C029              1
    V032    COST              1  C030              1
    V033    COST              1  C031              1
    V034    COST              1  C032              1
    V035    COST              1  C033              1
    V036    COST              1  C034              1
    V037    COST              1  C035              1
    V038    COST              1  C008              1
    V039    COST              1  C009              1
    V040    COST              1  C010              1
    V040    C016             -1  C018             -1
    V041    COST              1  C010              1
    V042    COST              1  C010              1
    V043    COST              1  C010              1
    V044    COST              1  C010              1
    V045    COST              1  C010              1
    V046    COST              1  C010              1
    V047    COST              1  C010              1
    V048    COST              1  C010              1
    V049    COST              1  C010              1
    V050    COST              1  C010              1
    V051    COST              1  C010              1
    V052    COST              1  C010              1
    V053    COST              1  C010              1
    V054    COST              1  C010              1
    V055    COST              1  C010              1
    V056    COST              1  C010              1
    V057    COST              1  C010              1
    V058    COST              1  C010              1
    V059    COST              1  C010              1
    V060    COST              1  C010              1
    V061    COST              1  C010              1
    V062    COST              1  C010              1
    V063    COST              1  C010              1
    V064    COST              1  C010              1
    V065    COST              1  C010              1
    V066    COST              1  C010              1
    V067    COST              1  C010              1
    V068    COST              1  C010              1
    V069    COST              1  C010              1
    V070    COST              1  C011              1
    V070    C016             -1  C018             -1
    V071    COST              1  C011              1
    V072    COST              1  C011              1
    V073    COST              1  C011              1
    V074    COST              1  C011              1
    V075    COST              1  C011              1
    V076    COST              1  C011              1
    V077    COST              1  C011              1
    V078    COST              1  C011              1
    V079    COST              1  C011              1
    V080    COST              1  C011              1
    V081    COST              1  C011              1
    V082    COST              1  C011              1
    V083    COST              1  C011              1
    V084    COST              1  C011              1
    V085    COST              1  C011              1
    V086    COST              1  C011              1
    V087    COST              1  C011              1
    V088    COST              1  C011              1
    V089    COST              1  C011              1
    V090    COST              1  C011              1
    V091    COST              1  C011              1
    V092    COST              1  C011              1
    V093    COST              1  C012              1
    V093    C016             -1  C018             -1
    V094    COST              1  C012              1
    V095    COST              1  C012              1
    V096    COST              1  C012              1
    V097    COST              1  C012              1
    V098    COST              1  C012              1
    V099    COST              1  C012              1
    V100    COST              1  C012              1
    V101    COST              1  C012              1
    V102    COST              1  C012              1
    V103    COST              1  C012              1
    V104    COST              1  C012              1
    V105    COST              1  C012              1
    V106    COST              1  C012              1
    V107    COST              1  C012              1
    V108    COST              1  C012              1
    V109    COST              1  C012              1
    V110    COST              1  C012              1
    V111    COST              1  C012              1
    V112    COST              1  C013              1
    V113    COST              1  C013              1
    V114    COST              1  C014              1
    V114    C016             -1  C018             -1
    V115    COST              1  C014              1
    V116    COST              1  C014              1
    V117    COST              1  C014              1
    V118    COST              1  C014              1
    V119    COST              1  C014              1
    V120    COST              1  C014              1
    V121    COST              1  C014              1
    V122    COST              1  C014              1
    V123    COST              1  C014              1
    V124    COST              1  C014              1
    V125    COST              1  C014              1
    V126    COST              1  C015              1
    V126    C016             -1  C018             -1
    V127    COST              1  C015              1
    V128    COST              1  C015              1
    V129    COST              1  C015              1
    V130    COST              1  C015              1
    V131    COST              1  C015              1
    V132    COST              1  C015              1
    V133    COST              1  C015              1
    V134    COST              1  C015              1
    V135    COST              1  C015              1
    V136    COST              1  C015              1
    V137    COST              1  C015              1
    V138    COST              1  C015              1
    V139    COST              1  C015              1
    V140    COST              1  C015              1
    V141    COST              1  C015              1
    V142    COST              1  C015              1
    V143    COST              1  C015              1
    V144    COST              1  C015              1
    V145    COST              1  C015              1
    V146    COST              1  C015              1
    V147    COST              1  C015              1
    V148    COST              1  C015              1
    V149    COST              1  C015              1
    V150    COST              1  C015              1
    V151    COST              1  C015              1
    V152    COST              1  C017              1
    V152    C018             -1
    V153    COST              1  C017              1
    V154    COST              1  C017              1
    V155    COST              1  C017              1
    V156    COST              1  C017              1
    V157    COST              1  C017              1
    V158    COST              1  C017              1
    V159    COST              1  C017              1
    V160    COST              1  C017              1
    V161    COST              1  C017              1
    V162    COST              1  C017              1
    V163    COST              1  C017              1
    V164    COST              1  C017              1
    V165    COST              1  C017              1
    V166    COST              1  C018             -1
    V166    C020              1
    V167    COST              1  C020              1
    V168    COST              1  C020              1
    V169    COST              1  C020              1
    V170    COST              1  C020              1
    V171    COST              1  C020              1
    V172    COST              1  C020              1
    V173    COST              1  C020              1
    V174    COST              1  C020              1
    V175    COST              1  C020              1
    V176    COST              1  C020              1
    V177    COST              1  C021              1
    V178    COST              1  C018             -1
    V178    C022              1
    V179    COST              1  C022              1
    V180    COST              1  C022              1
    V181    COST              1  C022              1
    V182    COST              1  C022              1
    V183    COST              1  C022              1
    V184    COST              1  C022              1
    V185    COST              1  C022              1
    V186    COST              1  C022              1
    V187    COST              1  C022              1
    V188    COST              1  C022              1
    V189    COST              1  C022              1
    V190    COST              1  C018             -1
    V190    C023              1
    V191    COST              1  C023              1
    V192    COST              1  C023              1
    V193    COST              1  C023              1
    V194    COST              1  C023              1
    V195    COST              1  C023              1
    V196    COST              1  C023              1
    V197    COST              1  C023              1
    V198    COST              1  C023              1
    V199    COST              1  C023              1
    V200    COST              1  C028              1
    V201    COST              1  C028              1
    V202    COST              1  C028              1
    V203    COST              1  C028              1
    V204    COST              1  C018             -1
    V204    C025              1
    V205    COST              1  C025              1
    V206    COST              1  C025              1
    V207    COST              1  C025              1
    V208    COST              1  C025              1
    V209    COST              1  C025              1
    V210    COST              1  C025              1
    V211    COST              1  C025              1
    V212    COST              1  C025              1
    V213    COST              1  C025              1
    V214    COST              1  C025              1
    V215    COST              1  C025              1
    V216    COST              1  C025              1
    V217    COST              1  C025              1
    V218    COST              1  C025              1
    V219    COST              1  C025              1
    V220    COST              1  C025              1
    V221    COST              1  C025              1
    V222    COST              1  C025              1
    V223    COST              1  C025              1
    V224    COST              1  C025              1
    V225    COST              1  C025              1
    V226    COST              1  C025              1
    V227    COST              1  C018             -1
    V227    C026              1  C030              1
    V228    COST              1  C030              1
    V229    COST              1  C030              1
    V230    COST              1  C030              1
    V231    COST              1  C030              1
    V232    COST              1  C030              1
    V233    COST              1  C030              1
    V234    COST              1  C030              1
    V235    COST              1  C030              1
    V236    COST              1  C030              1
    V237    COST              1  C030              1
    V238    COST              1  C030              1
    V239    COST              1  C030              1
    V240    COST              1  C030              1
    V241    COST              1  C030              1
    V242    COST              1  C030              1
    V243    COST              1  C030              1
    V244    COST              1  C030              1
    V245    COST              1  C030              1
    V246    COST              1  C030              1
    V247    COST              1  C030              1
    V248    COST              1  C030              1
    V249    COST              1  C030              1
    V250    COST              1  C030              1
    V251    COST              1  C030              1
    V252    COST              1  C030              1
    V253    COST              1  C030              1
    V254    COST              1  C030              1
    V255    COST              1  C030              1
    V256    COST              1  C030              1
    V257    COST              1  C030              1
    V258    COST              1  C030              1
    V259    COST              1  C030              1
    V260    COST              1  C030              1
    V261    COST              1  C030              1
    V262    COST              1  C018             -1
    V262    C026              1  C031              1
    V263    COST              1  C031              1
    V264    COST              1  C031              1
    V265    COST              1  C031              1
    V266    COST              1  C031              1
    V267    COST              1  C031              1
    V268    COST              1  C031              1
    V269    COST              1  C031              1
    V270    COST              1  C031              1
    V271    COST              1  C031              1
    V272    COST              1  C031              1
    V273    COST              1  C031              1
    V274    COST              1  C031              1
    V275    COST              1  C031              1
    V276    COST              1  C031              1
    V277    COST              1  C031              1
    V278    COST              1  C018             -1
    V278    C026              1  C032              1
    V279    COST              1  C032              1
    V280    COST              1  C032              1
    V281    COST              1  C032              1
    V282    COST              1  C032              1
    V283    COST              1  C032              1
    V284    COST              1  C032              1
    V285    COST              1  C032              1
    V286    COST              1  C032              1
    V287    COST              1  C032              1
    V288    COST              1  C032              1
    V289    COST              1  C032              1
    V290    COST              1  C032              1
    V291    COST              1  C032              1
    V292    COST              1  C033              1
    V293    COST              1  C033              1
    V294    COST              1  C033              1
    V295    COST              1  C033              1
    V296    COST              1  C033              1
    V297    COST              1  C033              1
    V298    COST              1  C033              1
    V299    COST              1  C033              1
    V300    COST              1  C034              1
    V301    COST              1  C034              1
    V302    COST              1  C034              1
    V303    COST              1  C034              1
    V304    COST              1  C034              1
    V305    COST              1  C034              1
    V306    COST              1  C034              1
    V307    COST              1  C034              1
    V308    COST              1  C035              1
    V309    COST              1  C035              1
RHS
    RHS     C000        342.726  C001              0
    RHS     C002        255.896  C003              0
    RHS     C004              0  C005         402.81
    RHS     C006            356  C007              0
    RHS     C008          119.3  C009            9.3
    RHS     C010              0  C011            4.6
    RHS     C012              0  C013          2.526
    RHS     C014              0  C015              0
    RHS     C016            207  C017              0
    RHS     C018          78.65  C019            183
    RHS     C020              1  C021              0
    RHS     C022              0  C023              0
    RHS     C024          55.13  C025           5.56
    RHS     C026            234  C027          21.11
    RHS     C028       -115.554  C029            356
    RHS     C030           4.32  C031          37.14
    RHS     C032          104.3  C033          24.68
    RHS     C034          11.75  C035              5
    RHS     C036              0
RANGES
    RANGE   C036        115.554
BOUNDS
 PL BOUND   V000
 PL BOUND   V001
 PL BOUND   V002
 PL BOUND   V003
 PL BOUND   V004
 PL BOUND   V005
 PL BOUND   V006
 PL BOUND   V007
 PL BOUND   V008
 PL BOUND   V009
 PL BOUND   V010
 PL BOUND   V011
 PL BOUND   V012
 PL BOUND   V013
 PL BOUND   V014
 PL BOUND   V015
 PL BOUND   V016
 PL BOUND   V017
 PL BOUND   V018
 PL BOUND   V019
 PL BOUND   V020
 PL BOUND   V021
 PL BOUND   V022
 PL BOUND   V023
 PL BOUND   V024
 PL BOUND   V025
 PL BOUND   V026
 PL BOUND   V027
 PL BOUND   V028
 PL BOUND   V029
 PL BOUND   V030
 PL BOUND   V031
 PL BOUND   V032
 PL BOUND   V033
 PL BOUND   V034
 PL BOUND   V035
 PL BOUND   V036
 PL BOUND   V037
 LO BOUND   V038          119.3
 UP BOUND   V038            550
 LO BOUND   V039            9.3
 UP BOUND   V039            690
 PL BOUND   V040
 FX BOUND   V041              0
 FX BOUND   V042              0
 FX BOUND   V043              0
 FX BOUND   V044              0
 FX BOUND   V045              0
 FX BOUND   V046              0
 FX BOUND   V047              0
 FX BOUND   V048              0
 FX BOUND   V049              0
 FX BOUND   V050              0
 FX BOUND   V051              0
 FX BOUND   V052              0
 FX BOUND   V053              0
 FX BOUND   V054              0
 FX BOUND   V055              0
 FX BOUND   V056              0
 FX BOUND   V057              0
 FX BOUND   V058              0
 FX BOUND   V059              0
 FX BOUND   V060              0
 FX BOUND   V061              0
 FX BOUND   V062              0
 FX BOUND   V063              0
 FX BOUND   V064              0
 FX BOUND   V065              0
 FX BOUND   V066              0
 FX BOUND   V067              0
 FX BOUND   V068              0
 FX BOUND   V069              0
 LO BOUND   V070            4.6
 FX BOUND   V071              0
 FX BOUND   V072              0
 FX BOUND   V073              0
 FX BOUND   V074              0
 FX BOUND   V075              0
 FX BOUND   V076              0
 FX BOUND   V077              0
 FX BOUND   V078              0
 FX BOUND   V079              0
 FX BOUND   V080              0
 FX BOUND   V081              0
 FX BOUND   V082              0
 FX BOUND   V083              0
 FX BOUND   V084              0
 FX BOUND   V085              0
 FX BOUND   V086              0
 FX BOUND   V087              0
 FX BOUND   V088              0
 FX BOUND   V089              0
 FX BOUND   V090              0
 FX BOUND   V091              0
 FX BOUND   V092              0
 PL BOUND   V093
 FX BOUND   V094              0
 FX BOUND   V095              0
 FX BOUND   V096              0
 FX BOUND   V097              0
 FX BOUND   V098              0
 FX BOUND   V099              0
 FX BOUND   V100              0
 FX BOUND   V101              0
 FX BOUND   V102              0
 FX BOUND   V103              0
 FX BOUND   V104              0
 FX BOUND   V105              0
 FX BOUND   V106              0
 FX BOUND   V107              0
 FX BOUND   V108              0
 FX BOUND   V109              0
 FX BOUND   V110              0
 FX BOUND   V111              0
 FX BOUND   V112              0
 FX BOUND   V113              0
 PL BOUND   V114
 FX BOUND   V115              0
 FX BOUND   V116              0
 FX BOUND   V117              0
 FX BOUND   V118              0
 FX BOUND   V119              0
 FX BOUND   V120              0
 FX BOUND   V121              0
 FX BOUND   V122              0
 FX BOUND   V123              0
 FX BOUND   V124              0
 FX BOUND   V125              0
 PL BOUND   V126
 FX BOUND   V127              0
 FX BOUND   V128              0
 FX BOUND   V129              0
 FX BOUND   V130              0
 FX BOUND   V131              0
 FX BOUND   V132              0
 FX BOUND   V133              0
 FX BOUND   V134              0
 FX BOUND   V135              0
 FX BOUND   V136              0
 FX BOUND   V137              0
 FX BOUND   V138              0
 FX BOUND   V139              0
 FX BOUND   V140              0
 FX BOUND   V141              0
 FX BOUND   V142              0
 FX BOUND   V143              0
 FX BOUND   V144              0
 FX BOUND   V145              0
 FX BOUND   V146              0
 FX BOUND   V147              0
 FX BOUND   V148              0
 FX BOUND   V149              0
 FX BOUND   V150              0
 FX BOUND   V151              0
 PL BOUND   V152
 UP BOUND   V153        0.60387
 UP BOUND   V154       0.432509
 UP BOUND   V155        0.56801
 UP BOUND   V156       0.503682
 UP BOUND   V157        0.29427
 UP BOUND   V158       0.359968
 UP BOUND   V159       0.177931
 UP BOUND   V160       0.177931
 UP BOUND   V161       0.109496
 UP BOUND   V162       0.191618
 UP BOUND   V163        0.13687
 UP BOUND   V164       0.095809
 UP BOUND   V165       0.177931
 PL BOUND   V166
 FX BOUND   V167       0.655607
 FX BOUND   V168       0.068435
 LO BOUND   V169      0.0370544
 UP BOUND   V169       0.260053
 LO BOUND   V170      0.0750839
 UP BOUND   V170       0.526949
 LO BOUND   V171       0.163819
 UP BOUND   V171        1.14971
 UP BOUND   V172       0.216255
 UP BOUND   V173       0.216255
 UP BOUND   V174       0.216255
 UP BOUND   V175       0.437984
 UP BOUND   V176       0.191618
 UP BOUND   V177       0.311653
 PL BOUND   V178
 UP BOUND   V179       0.164244
 UP BOUND   V180       0.226109
 UP BOUND   V181       0.167529
 UP BOUND   V182       0.130026
 UP BOUND   V183        0.12113
 UP BOUND   V184       0.173688
 UP BOUND   V185       0.068435
 UP BOUND   V186       0.164244
 UP BOUND   V187       0.095809
 UP BOUND   V188      0.0171087
 UP BOUND   V189      0.0307958
 PL BOUND   V190
 UP BOUND   V191         1.5001
 UP BOUND   V192         1.2332
 UP BOUND   V193        9.36465
 UP BOUND   V194        1.79984
 UP BOUND   V195       0.650133
 UP BOUND   V196        0.60565
 UP BOUND   V197        0.31398
 UP BOUND   V198        2.15844
 UP BOUND   V199        1.37281
 UP BOUND   V200              2
 UP BOUND   V201              5
 UP BOUND   V202              8
 FX BOUND   V203              0
 PL BOUND   V204
 FX BOUND   V205       0.713914
 FX BOUND   V206       0.474939
 LO BOUND   V207       0.933453
 UP BOUND   V207       0.933453
 FX BOUND   V208       0.013687
 FX BOUND   V209      0.0739098
 FX BOUND   V210      0.0602228
 FX BOUND   V211        2.37387
 FX BOUND   V212       0.372013
 FX BOUND   V213       0.171088
 FX BOUND   V214       0.068435
 LO BOUND   V215       0.260469
 UP BOUND   V215          2.456
 LO BOUND   V216      0.0439969
 UP BOUND   V216       0.414853
 UP BOUND   V217       0.960143
 UP BOUND   V218       0.960143
 UP BOUND   V219       0.459199
 UP BOUND   V220       0.539268
 UP BOUND   V221       0.013687
 UP BOUND   V222       0.335332
 UP BOUND   V223       0.298787
 UP BOUND   V224       0.132764
 UP BOUND   V225        1.47272
 UP BOUND   V226       0.041061
 PL BOUND   V227
 LO BOUND   V228        0.74061
 UP BOUND   V228        1.65528
 LO BOUND   V229        3.57939
 UP BOUND   V229              8
 UP BOUND   V230         0.5208
 FX BOUND   V231              0
 UP BOUND   V232        11.9933
 UP BOUND   V233          0.124
 UP BOUND   V234          0.124
 UP BOUND   V235       0.073036
 UP BOUND   V236         0.0992
 UP BOUND   V237         0.1612
 UP BOUND   V238          0.031
 UP BOUND   V239          0.031
 UP BOUND   V240          0.062
 UP BOUND   V241       0.781572
 UP BOUND   V242       0.104904
 UP BOUND   V243       0.022196
 UP BOUND   V244       0.733956
 UP BOUND   V245       0.544112
 UP BOUND   V246       0.192076
 UP BOUND   V247       0.432372
 UP BOUND   V248        12.2767
 UP BOUND   V249       0.531056
 UP BOUND   V250         0.0744
 UP BOUND   V251         0.9548
 UP BOUND   V252        0.49972
 UP BOUND   V253       0.490405
 UP BOUND   V254        1.64244
 UP BOUND   V255         1.3687
 UP BOUND   V256        2.79625
 UP BOUND   V257         0.5208
 UP BOUND   V258         0.0372
 UP BOUND   V259        2.34379
 UP BOUND   V260        2.34379
 UP BOUND   V261         4.8732
 LO BOUND   V262    7.10543e-15
 LO BOUND   V263        30.9624
 UP BOUND   V263           62.2
 LO BOUND   V264        2.89215
 UP BOUND   V264           5.81
 LO BOUND   V265         1.6427
 UP BOUND   V265            3.3
 LO BOUND   V266         1.6427
 UP BOUND   V266            3.3
 UP BOUND   V267         0.2852
 UP BOUND   V268        13.3703
 UP BOUND   V269          5.828
 UP BOUND   V270        11.3079
 UP BOUND   V271        1.61436
 UP BOUND   V272            175
 FX BOUND   V273              0
 FX BOUND   V274              0
 UP BOUND   V275          1.302
 UP BOUND   V276         0.8556
 UP BOUND   V277        0.77004
 LO BOUND   V278        31.0433
 LO BOUND   V279        14.9897
 UP BOUND   V279        14.9897
 LO BOUND   V280        49.3839
 UP BOUND   V280        49.3839
 FX BOUND   V281        0.83452
 FX BOUND   V282         1.5159
 FX BOUND   V283           0.31
 FX BOUND   V284        0.69192
 FX BOUND   V285         0.0558
 FX BOUND   V286        0.54312
 FX BOUND   V287        1.60084
 FX BOUND   V288        3.08301
 FX BOUND   V289              0
 FX BOUND   V290         0.1116
 FX BOUND   V291         0.1364
 LO BOUND   V292          24.68
 UP BOUND   V292          44.17
 UP BOUND   V293        17.0902
 FX BOUND   V294              0
 UP BOUND   V295       0.232872
 UP BOUND   V296       0.506912
 UP BOUND   V297        1.37789
 UP BOUND   V298        1.04048
 FX BOUND   V299              0
 FX BOUND   V300              0
 FX BOUND   V301              0
 LO BOUND   V302          11.75
 UP BOUND   V302        47.0677
 FX BOUND   V303              0
 UP BOUND   V304          0.992
 UP BOUND   V305         0.2356
 UP BOUND   V306         0.0124
 UP BOUND   V307          0.434
 LO BOUND   V308              5
 UP BOUND   V308        10.4433
 UP BOUND   V309           1.24
ENDATA
''')

"""

# Define variables
x = model.new_num_var(0, 10, 'x')  # Integer variable, 0 <= x <= 10
y = model.new_num_var(0, 5, 'y')  # Continuous variable, 0 <= y <= 5

# Define constraints
model.add(2 * x + y <= 15)
model.add(x - y >= 2)

# Define objective function
model.maximize(3 * x + 2 * y)
"""

# Create a solver
solver = model_builder.ModelSolver("GLOP")

# Solve the problem
solver.enable_output(True)
status = solver.solve(model)

# Check the solution status and print results
if True:#status == solver.OPTIMAL:
    print('Solution:')
    print('status =', status)

    print('objective_value: ', solver.objective_value )
    print('status_string: ', solver.status_string )
    print('wall_time: ', solver.wall_time )
    print('user_time: ', solver.user_time )

    print('variables: ', model.get_variables() )

    #print('y =', solver.value('TRXN_2600'))

else:
    print('The problem does not have an optimal solution.')